USE sis11

go

delete
FROM TransactionTemplate 
WHERE code
IN (
    'Ajuste Monetario',
    'Ajuste.Stro',
    'AMORTIZACION',
    'Anticipo Primas',
    'Capitalización Renta Vitalicia',
    'Cierre Anual',
    'Clonada Emisión',
    'Cobro Prima',
    'Cobro_Prima',
    'Constitución Rsva.Matemáticas',
    'Depósito Bancario',
    'Dev.Prima',
    'Emision',
    'Emisión ME',
    'Emision Reaseguro',
    'Endoso Cancelación',
    'Endoso Cancelación ME',
    'Endoso Cancelación MN',
    'Endoso ME',
    'Endoso MN',
    'Faltante de Caja',
    'Fondos Asignados',
    'Gtos.Ajuste Siniestros',
    'Ing.Renta Vitalicia',
    'Ingreso_Caja',
    'Lib.Rsva.RiesgoCurso',
    'Liberación Rsva.Stros.',
    'LIq.Ajuste de Siniestro',
    'Liq.Comisiones',
    'LIQ.REANP-GASTO',
    'LIQ.REANP-PASIVO',
    'LIQ.RNP',
    'Liq.Siniestros',
    'LIquid.-Reasegurador',
    'Liquidación Coasegurador',
    'Liquidación Stro.',
    'ME',
    'Pago Anualidad',
    'Pago Coasegurador',
    'Pago Reasegurador',
    'Pago-Remesa',
    'PagoReservaIncendio',
    'Pgo.Comisión Agente',
    'Pgo.Stros.',
    'PMD',
    'Prueba EMISIÓN ME',
    'REASEGURONP',
    'Reintegro de Fondos',
    'Rem.Coaseg.Minoritario',
    'Respaldo Endoso',
    'Reversión Cobro Prima',
    'Rsva.Gasto Ajustes',
    'Rsva.Stros.',
    'Rvrs.Pgo.Stro.',
    'Traslado de Saldos',
    'Traslado Saldo',
    'Venta Divisas'
)
